title: English Corner - Fun and Effective Learning for Kids in Bangbuathong
email: englishcorner.bbt@gmail.com
phone: +66-083-236-0009
phone_short: 083-236-0009
facebook: https://www.facebook.com/englishcorner.bangbuathong
line: https://lin.ee/A0eizei
logo: /assets/image/logo/logo_english.png
social:
  name: English Corner
  links:
    - https://www.facebook.com/englishcorner.bangbuathong
google_analytics: G-WFMNYDS086

tagline: >-
  English Corner สถาบันสอนภาษาอังกฤษสำหรับเด็ก หลักสูตร Arts, Math, English และ
  Phonics เน้นกิจกรรมสนุก เรียนรู้ผ่านกิจกรรม ครูต่างชาติที่มีประสบการณ์
  สาขาบางบัวทอง
description: >-
  English Corner สถาบันสอนภาษาอังกฤษสำหรับเด็ก หลักสูตร Arts, Math, English และ
  Phonics เน้นกิจกรรมสนุก เรียนรู้ผ่านกิจกรรม ครูต่างชาติที่มีประสบการณ์
  สาขาบางบัวทอง
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

future: true
